name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Grant execute permission to build script
        run: chmod +x ./build.sh

        
      - name: Build
        run: bash ./build.sh

      - name: Deploy (GitHub Pages)
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
